openapi: 3.0.0
info:
  title: PEFSA / XXX
  description: PEFSA XXX
  termsOfService: 'http://pefsa.io/terms/'
  contact:
    email: xxx@us.panasonic.com
  version: 1.0.0
servers:
  - url: 'https://xxxxx.execute-api.xx-xxxx-x.amazonaws.com/dev'
  - url: 'http://localhost:3000/dev'
tags:
  - name: XXX
    description: XXX
paths:
  '/':
    post:
      tags:
        - XXX
      summary: This is XXX summary.
      description: This is XXX description.
      requestBody:
        description: XXX
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sampleData'
      responses:
        '200':
          description: XXX
          content:
            application/json:
              schema:
                type: object
        '400':
          $ref: '#/components/responses/InvalidInput'
        '403':
          $ref: '#/components/responses/NotAuthorized'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    sampleData:
      type: object
      properties:
        value:
          type: number
  responses:
    Success:
      description: success
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
    InvalidInput:
      description: Invalid input error
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              err:
                type: object
    NotAuthorized:
      description: Not authorized to process
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              err:
                type: object
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              err:
                type: object
security:
  - bearerAuth: []
